# Generated by Django 4.1.6 on 2023-02-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdnProvince',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=75, unique=True)),
                ('code', models.CharField(max_length=5, unique=True)),
                ('isoCode', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=75)),
                ('geographicArea', models.CharField(max_length=75)),
                ('capital', models.CharField(max_length=75, null=True)),
                ('image', models.CharField(max_length=255, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('deletedAt', models.DateTimeField(default=None, null=True)),
            ],
            options={
                'db_table': 'md_idn_province',
            },
        ),
    ]
