# Generated by Django 4.1.6 on 2023-02-14 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('idn_district', '0001_initial'),
        ('idn_subdistrict', '0001_initial'),
        ('idn_province', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdnUrbanVillage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=75, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=75)),
                ('alias', models.CharField(max_length=75, null=True)),
                ('postalCode', models.CharField(max_length=10)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('deletedAt', models.DateTimeField(default=None, null=True)),
                ('IdnDistrict', models.ForeignKey(db_column='idnDistrictId', on_delete=django.db.models.deletion.CASCADE, related_name='urbanVillages', to='idn_district.idndistrict')),
                ('idnProvince', models.ForeignKey(db_column='idnProvinceId', on_delete=django.db.models.deletion.CASCADE, related_name='urbanVillages', to='idn_province.idnprovince')),
                ('idnSubdistrict', models.ForeignKey(db_column='idnSubdistrictId', on_delete=django.db.models.deletion.CASCADE, related_name='urbanVillages', to='idn_subdistrict.idnsubdistrict')),
            ],
            options={
                'db_table': 'md_idn_urban_village',
            },
        ),
    ]
